### ISSUE TITLE
line 63 in the 2nd / 601_11_01.bin crash

### ISSUE THREAD

**Issue by shun9092** [thesupersonic16/DALTools#16]
On line 63(「うむ！　冬服を見に行こう！」) in the 2nd / 601_11_01.bin file, the game is forcibly turned off.

The same thing happens when you rebuild from the original file.

**Comment by thesupersonic16** [comment]
I seem to be unable to reproduce this issue. What are you using to rebuild the file? STSCTool? because I have rebuilt the file with the lastest release and everything seems to be working fine for me.

![image](https://user-images.githubusercontent.com/25761885/76698610-3462c700-66f9-11ea-8a70-7b1c0be1190e.png)

**Comment by shun9092** [comment]
Isn't it forced to quit after line 63?

Basically, I am using the program you made.

The script can be replaced only by writing it in a spreadsheet on Google Drive.

Here is my rebuild script file.

https://www.dropbox.com/s/dolslod0ciiydjm/Script.pck?dl=0

**Comment by thesupersonic16** [comment]
I just checked Script_E.pck and it seems to work perfectly fine on my end. Is that file meant to have the issue?

**Comment by shun9092** [comment]
It doesn't seem to be a script problem.

I think I found the problem. Sorry.

I will check and contact you again.

Thank you.

**Comment by thesupersonic16** [comment]
That's fine. If it does end up not being a DALTools issue then feel free to click that Close button. I hope DALTools will help you get want you want done.
