### ISSUE TITLE
Incorrect file order in PCK Archive

### ISSUE THREAD

**Issue by shun9092** [thesupersonic16/DALTools#17]
I seem to have found the problem.

It was a graphics issue.

Repacking was done through the program, but it is forcibly turned off when loaded.

I think it was a pck file problem.

Original file
https://www.dropbox.com/s/il688x7dreu35of/MA010500_O.pck?dl=0

Rebuild the original file(build without modification)
https://www.dropbox.com/s/tr3bhwsx64y3op3/MA010500_Re_O.pck?dl=0

I unpacked and repacked original pck file without modification and it still crashes.

**Comment by thesupersonic16** [comment]
I see. the order the files are are incorrect. Not very sure how I will figure it out yet.

**Comment by thesupersonic16** [comment]
So I have for the time being hardcoded a sorter for MA and MP pcks. Hopefully you can continue working with this.
Since this doesn't have a proper sorter I will be keeping this issue open until I make a final decision.

 
[DALTools.zip](https://github.com/thesupersonic16/DALTools/files/4334121/DALTools.zip)
Also keep in mind this includes a small change in STSCTool aswell so compile all your scripts before using this version of STSCTool to prevent errors.

**Comment by shun9092** [comment]
It's work well, no crash.

If I have any issue, I'll write.

**Comment by shun9092** [comment]
Finally I am preparing to release the game patch.

Thank you very much.

I would have been very hard without your help.

So I put your name on the list.

Thank you.

https://imgur.com/HR97A53
